[package]
name = "easel"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "easel"
path = "src/main.rs"

[dependencies]
paint = { path = "../paint" }
mlua = { version = "0.10", features = ["luajit", "vendored"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
